# Generated by Django 5.0.6 on 2025-10-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("PATIENTS", "Patients"),
                            ("DOCTORS", "Doctors"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("-published_at",),
            },
        ),
        migrations.CreateModel(
            name="CmsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
            options={
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("ordering", "question"),
            },
        ),
    ]
